server:
  port: 1000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packagesToScan: com.messenger.message_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: 25032001
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  application:
    name: message-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            url: http://localhost:6500
          user-service:
            url: http://localhost:7000
          group-service:
            url: http://localhost:9000

storage-property:
  storageDirectory: MessageService/


